### ISSUE TITLE
autoplayHoverPause not working properly

### ISSUE THREAD

**Issue by gmerabishvili** [vitalii-andriiovskyi/ngx-owl-carousel-o#15]
Hi, autoplay doesn't renew on mouse leave. Can you fix that issue?

**Comment by gmerabishvili** [comment]
Thank you very much! yes, it's fixed, but in some cases there's same issue after tab switch. Great carousel anyway 👍

**Comment by vitalii-andriiovskyi** [comment]
I found the problem:  when the user leaves the carousel before it gets translated (scrolled), the autoplay doesn't renew. It fixed in `v1.0.7`. I've already published this version.

It's worth to remember that after tab switch, the autoplay will renew in that amount of time which is set in the option `autoplayTimeout`. That is small pause will be after tab switching and leaving the carousel by the cursor. 

Please, check if updates solve your issue after tab switch.

**Comment by gmerabishvili** [comment]
I just tested it and it behaves like this: when I switch the tab carousel stops and whenever I return to that tab it doesn't renew autoplay until I hover on it. I think it still have some bug...

**Comment by vitalii-andriiovskyi** [comment]
How did you realize the tab?

Is it native carousel's dots or DOM elements which have `click` handler for calling method `to(slideId)`?

**Comment by gmerabishvili** [comment]
What does tab realize mean? I just switched tabs. and I use native carousel's nav to slide...

**Comment by vitalii-andriiovskyi** [comment]
_tab realize_ -- I meant how did you created the tab? Or maybe what do you mean by the tab.

**Comment by gmerabishvili** [comment]
I mean the browser tab, in my case chrome  tab switch.

**Comment by gmerabishvili** [comment]
Okay. As it seems the same issue occurs on the original Jquery owl-carousel too. Here is the open issue about that: https://github.com/OwlCarousel2/OwlCarousel2/issues/1727.  I hope you'll implement that functionality later : ))) Thank you!

**Comment by vitalii-andriiovskyi** [comment]
The issue is fixed. Update the lib to the version `v1.0.8`, please. 

However, there's still small problem with the browser __Edge__. Info is here [CHANGELOG](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/blob/update-to-v7-of-nrwl-and-angular/CHANGELOG.md)

**Comment by gmerabishvili** [comment]
Thank you very much. I tested and it worked!
